version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 100
    registries:
      - npm_public_registry

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 100

registries:
  npm_public_registry:
    type: "npm-registry"
    url: "https://registry.npmjs.org/"
    token: "${{ secrets.TOKEN }}"
